sql_pos <- "SELECT SEGMENT1,SEGMENT2,SEGMENT3,SEGMENT4,GIN, TT_CUSTOMER, POS_YEAR, SEASON, POS_MTH_NBR, POS_WK_NBR, SUM(POS_UNITS) as UNITS,SUM(POS_SALES) as SALES,SUM(POS_INV_UNITS) as RTL_INV, MAX(LISTED) AS LISTED, MAX(STORECT) AS STORECT,AVG(INSTOCK) AS INSTOCK, POS_WK_END_DT as WK_END_DT
          FROM R_POS_WITH_LLINSTOCK
          WHERE SEGMENT2 NOT IN  ('SPECIALS','LEGACY')
          AND SEGMENT2 NOT LIKE ('OTHER%')
          AND POS_YEAR > 2011
          GROUP BY SEGMENT1,SEGMENT2,SEGMENT3,SEGMENT4,GIN, POS_YEAR, SEASON, POS_MTH_NBR, POS_WK_NBR, TT_CUSTOMER, POS_WK_END_DT
          HAVING SUM(POS_UNITS) <> 0
          ORDER BY SEGMENT4, TT_CUSTOMER, POS_YEAR, POS_MTH_NBR, POS_WK_NBR"

sql_gin_subs <- "SELECT CAST(GIN_FROM as varchar) AS GIN, CAST(GIN_TO AS varchar) AS GIN_TO FROM tblGIN_SUBS WHERE LEN(GIN_TO) = 5"

sql_promo <- "SELECT * from vPROMO_TOYS"

sql_listings <- "SELECT POS_WK_END_DT as WK_END_DT, GIN, ACCOUNT as TT_CUSTOMER, LISTED, STORECT from vLineListWeekly"

